version: "3.8"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app/
  socket_server:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./:/app/
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
